sonar.organization=ticket-registrator
sonar.projectKey=ticket-registrator-shared
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx,src/styles/theme.ts
sonar.cpd.exclusions=src/i18n/**,src/defaults/default-categories.ts
sonar.exclusions=src/i18n/**,src/styles/theme.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
