import type { RoleType } from './roles';
import { Roles } from './roles';
import { permissions } from './permissions';
import type { PermissionType } from './permissions';

const all_permissions = Object.values(permissions) as PermissionType[];

export const ROLE_DEFAULT_PERMISSIONS: Record<RoleType, PermissionType[]> = {
  [Roles.EMPLOYEE]: [
    permissions.VIEW_REPORTS,
    permissions.CREATE_REPORTS,
    permissions.EDIT_REPORTS,
    permissions.DELETE_REPORTS,
    permissions.SUBMIT_REPORTS,
    permissions.VIEW_TICKETS,
    permissions.CREATE_TICKETS,
    permissions.EDIT_TICKETS,
    permissions.DELETE_TICKETS,
    permissions.VIEW_USERS,
    permissions.EDIT_USERS,
  ],

  [Roles.MANAGER]: [
    permissions.VIEW_REPORTS,
    permissions.CREATE_REPORTS,
    permissions.EDIT_REPORTS,
    permissions.DELETE_REPORTS,
    permissions.SUBMIT_REPORTS,
    permissions.VIEW_TICKETS,
    permissions.CREATE_TICKETS,
    permissions.EDIT_TICKETS,
    permissions.DELETE_TICKETS,
    permissions.CREATE_USERS,
    permissions.VIEW_USERS,
    permissions.EDIT_USERS,
    permissions.DELETE_USERS,
    permissions.VIEW_DEPARTMENTS
    ,
  ],

  [Roles.CONTROLLER]: [
    permissions.VIEW_REPORTS,
    permissions.CREATE_REPORTS,
    permissions.EDIT_REPORTS,
    permissions.DELETE_REPORTS,
    permissions.SUBMIT_REPORTS,
    permissions.VIEW_TICKETS,
    permissions.CREATE_TICKETS,
    permissions.EDIT_TICKETS,
    permissions.DELETE_TICKETS,
    permissions.VIEW_USERS,
    permissions.EDIT_USERS,
    permissions.DELETE_USERS,
    permissions.VIEW_DEPARTMENTS,
    permissions.APPROVE_REPORTS,
    permissions.APPROVE_TICKETS,
    permissions.APPROVE_ITEMS
    ,
  ],

  [Roles.ADMIN]: [
    permissions.VIEW_REPORTS,
    permissions.CREATE_REPORTS,
    permissions.EDIT_REPORTS,
    permissions.DELETE_REPORTS,
    permissions.SUBMIT_REPORTS,
    permissions.VIEW_TICKETS,
    permissions.CREATE_TICKETS,
    permissions.EDIT_TICKETS,
    permissions.DELETE_TICKETS,
    permissions.VIEW_USERS,
    permissions.CREATE_USERS,
    permissions.EDIT_USERS,
    permissions.DELETE_USERS,
    permissions.APPROVE_REPORTS,
    permissions.APPROVE_TICKETS,
    permissions.APPROVE_ITEMS,
    permissions.VIEW_ROLES,
    permissions.CREATE_ROLES,
    permissions.EDIT_ROLES,
    permissions.DELETE_ROLES,
    permissions.VIEW_PERMISSIONS,
    permissions.CREATE_PERMISSIONS,
    permissions.EDIT_PERMISSIONS,
    permissions.DELETE_PERMISSIONS,
    permissions.VIEW_DEPARTMENTS,
    permissions.CREATE_DEPARTMENTS,
    permissions.EDIT_DEPARTMENTS,
    permissions.DELETE_DEPARTMENTS,
    permissions.VIEW_CATEGORIES,
    permissions.CREATE_CATEGORIES,
    permissions.EDIT_CATEGORIES,
    permissions.DELETE_CATEGORIES,
    permissions.VIEW_POLICIES,
    permissions.CREATE_POLICIES,
    permissions.EDIT_POLICIES,
    permissions.DELETE_POLICIES,
  ],

  [Roles.SUPERADMIN]: all_permissions,
};
