import type { RoleType } from './roles';
import { Roles } from './roles';
import { permissions } from './permissions';
import type { PermissionType } from './permissions';

const all_permissions = Object.values(permissions) as PermissionType[];

export const ROLE_DEFAULT_PERMISSIONS: Record<RoleType, PermissionType[]> = {
  [Roles.EMPLOYEE]: [
    permissions.VIEW_OWN_REPORTS,
    permissions.EDIT_OWN_REPORTS,
    permissions.CREATE_OWN_REPORTS,
    permissions.DELETE_OWN_REPORTS,
    permissions.VIEW_OWN_TICKETS,
    permissions.EDIT_OWN_TICKETS,
    permissions.CREATE_OWN_TICKETS,
    permissions.DELETE_OWN_TICKETS,
    permissions.SUBMIT_OWN_REPORTS,
    permissions.VIEW_OWN_USER_INFO,
    permissions.EDIT_OWN_USER_INFO,
  ],

  [Roles.MANAGER]: [
    ...[
      permissions.VIEW_OWN_REPORTS,
      permissions.EDIT_OWN_REPORTS,
      permissions.CREATE_OWN_REPORTS,
      permissions.DELETE_OWN_REPORTS,
      permissions.VIEW_OWN_TICKETS,
      permissions.EDIT_OWN_TICKETS,
      permissions.CREATE_OWN_TICKETS,
      permissions.DELETE_OWN_TICKETS,
      permissions.SUBMIT_OWN_REPORTS,
      permissions.VIEW_OWN_USER_INFO,
      permissions.EDIT_OWN_USER_INFO,
      permissions.DELETE_USER,
    ],
    permissions.VIEW_TEAM_REPORTS,
    permissions.VIEW_TEAM_TICKETS,
    permissions.VIEW_TEAM_USERS,
  ],

  [Roles.CONTROLLER]: [
    ...[
      permissions.VIEW_OWN_REPORTS,
      permissions.EDIT_OWN_REPORTS,
      permissions.CREATE_OWN_REPORTS,
      permissions.DELETE_OWN_REPORTS,
      permissions.VIEW_OWN_TICKETS,
      permissions.EDIT_OWN_TICKETS,
      permissions.CREATE_OWN_TICKETS,
      permissions.DELETE_OWN_TICKETS,
      permissions.SUBMIT_OWN_REPORTS,
      permissions.VIEW_OWN_USER_INFO,
      permissions.EDIT_OWN_USER_INFO,
      permissions.DELETE_USER,
      permissions.VIEW_TEAM_REPORTS,
      permissions.VIEW_TEAM_TICKETS,
      permissions.VIEW_TEAM_USERS,
      permissions.VIEW_DEPARTMENTS,
    ],
    permissions.VIEW_ALL_USERS,
    permissions.VIEW_ALL_REPORTS,
    permissions.VIEW_ALL_TICKETS,
    permissions.APPROVE_REPORTS,
    permissions.APPROVE_TICKETS,
    permissions.APPROVE_ITEMS,
  ],

  [Roles.ADMIN]: [
    ...[
      permissions.VIEW_OWN_REPORTS,
      permissions.EDIT_OWN_REPORTS,
      permissions.CREATE_OWN_REPORTS,
      permissions.DELETE_OWN_REPORTS,
      permissions.VIEW_OWN_TICKETS,
      permissions.EDIT_OWN_TICKETS,
      permissions.CREATE_OWN_TICKETS,
      permissions.DELETE_OWN_TICKETS,
      permissions.SUBMIT_OWN_REPORTS,
      permissions.VIEW_OWN_USER_INFO,
      permissions.EDIT_OWN_USER_INFO,
      permissions.DELETE_USER,
      permissions.VIEW_TEAM_REPORTS,
      permissions.VIEW_TEAM_TICKETS,
      permissions.VIEW_TEAM_USERS,
      permissions.VIEW_ALL_USERS,
      permissions.VIEW_ALL_REPORTS,
      permissions.VIEW_ALL_TICKETS,
      permissions.APPROVE_REPORTS,
      permissions.APPROVE_TICKETS,
      permissions.APPROVE_ITEMS,
    ],
    permissions.CREATE_USERS,
    permissions.EDIT_USERS,
    permissions.DELETE_USERS,
    permissions.CREATE_ROLES,
    permissions.EDIT_ROLES,
    permissions.DELETE_ROLES,
    permissions.VIEW_ROLES,
    permissions.CREATE_PERMISSIONS,
    permissions.EDIT_PERMISSIONS,
    permissions.DELETE_PERMISSIONS,
    permissions.VIEW_PERMISSIONS,
    permissions.VIEW_DEPARTMENTS,
    permissions.CREATE_DEPARTMENTS,
    permissions.EDIT_DEPARTMENTS,
    permissions.DELETE_DEPARTMENTS,
  ],

  [Roles.SUPERADMIN]: all_permissions, // Full access within an organization
};
