name: Notify Dev Updates (Discord)

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEV_UPDATES }}
          status: ${{ job.status }}
          content: "@everyone ⚠️ **Nuevos cambios en `dev`**"
          title: "¡Hay actualizaciones disponibles!"
          description: |
            Se han subido nuevos cambios a la rama **dev**. 
            
            Actualiza tu entorno local para tener la última versión.
          color: 0x3498db # Azul claro
